# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://cs291.com # the base hostname & protocol for your site

# User settings
course_number: CS291A
quarter: Fall 2022
title: Scalable Internet Services

github_username: scalableinternetservices

instructor: Dr Nevena Golubovic
instructor_email: nevena@cs.ucsb.edu
instructor_url: https://www.linkedin.com/in/nevenagolubovic/

drive_url: https://drive.google.com/drive/folders/11ZU37_a1Yc6pTBNo9uIcsCKV422Ypdyf?usp=sharing
piazza_url: https://piazza.com/ucsb/fall2022/cs291a

intro_survey: https://forms.gle/djDdAYQoJyA9w3mn9
project0_submission: https://forms.gle/YemRRvN47DH98j6P9
project1_submission: https://forms.gle/u7Q66zVZJ2CyuQVw5
project2_submission: https://forms.gle/4VxZbsLEEHPPQQ7F6

kramdown:
  parse_block_html: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
