# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://cs291.com # the base hostname & protocol for your site

# User settings
course_number: CS291A
quarter: Fall 2021
title: Scalable Internet Services

github_username: scalableinternetservices

instructor: Dr. Bryce Boe
instructor_email: bboe@cs.ucsb.edu
instructor_url: https://www.linkedin.com/in/bryceboe/

drive_url: https://drive.google.com/drive/folders/17mWzDGfDk1mlNdtblPFWDSmpXVonx9qA
piazza_url: https://piazza.com/ucsb/fall2021/cs291a

intro_survey: https://forms.gle/h8N5ymVe5ofYA9MK9
project0_submission: https://forms.gle/3ui9iggNoETA7bX28

kramdown:
  parse_block_html: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
