# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cs291.com" # the base hostname & protocol for your site

# User settings
course_number: CS291A
quarter: Winter 2021
title: Scalable Internet Services

github_username: scalableinternetservices

instructor: "Bryce Boe"
instructor_url: "https://bryceboe.com"

drive_url: "https://drive.google.com/drive/folders/1gR2i40_QGN0TfK4CjLZMGaQGNcTyj2P_"
nectir_url: "https://ucsb.nectir.io/channel/cs291a_w2021"
piazza_url: "https://piazza.com/ucsb/winter2021/CS291A"

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
