jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
        uses: github/super-linter@v4

name: super-linter
on:
  pull_request:
    branches: [main]
  push:
    branches-ignore:
      - gh-pages
      - main
